"""Create initial tables

Revision ID: 297ac4f87b47
Revises: 
Create Date: 2026-02-24 20:44:10.613770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '297ac4f87b47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ext_name', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('civil_status', sa.Enum('SINGLE', 'MARRIED', 'SEPARATED', 'WIDOWED', name='civilstatusenum'), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sexenum'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('philhealth_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('medicalcondition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('question1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question5', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question6', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question7a', sa.Date(), nullable=True),
    sa.Column('question7b', sa.Date(), nullable=True),
    sa.Column('question7c', sa.Integer(), nullable=True),
    sa.Column('question8', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('smoke_years', sa.Float(), nullable=True),
    sa.Column('alcohol_years', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('assessmentfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback_rating', sa.Enum('STR_DISAGREE', 'DISAGREE', 'NEUTRAL', 'AGREE', 'STR_AGREE', name='ratingenum'), nullable=True),
    sa.Column('feedback_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('encountercondition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['condition_id'], ['medicalcondition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('physicalexam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('blood_type', sa.Enum('APLUS', 'ABPLUS', 'BPLUS', 'OPLUS', 'AMINUS', 'ABMINUS', 'BMINUS', 'OMINUS', name='bloodtypeenum'), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('respiration_rate', sa.Integer(), nullable=True),
    sa.Column('va_top', sa.Integer(), nullable=True),
    sa.Column('va_bottom', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('gen_survey', sa.Enum('AWAKE', 'ALTERED', name='gensurveyenum'), nullable=True),
    sa.Column('additional_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('toddlerexam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('body_waist_circ', sa.Float(), nullable=True),
    sa.Column('mid_upper_arm_circ', sa.Float(), nullable=True),
    sa.Column('head_circ', sa.Float(), nullable=True),
    sa.Column('hip', sa.Float(), nullable=True),
    sa.Column('skinfold_thick', sa.Float(), nullable=True),
    sa.Column('limbs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toddlerexam')
    op.drop_table('physicalexam')
    op.drop_table('encountercondition')
    op.drop_table('assessmentfeedback')
    op.drop_table('assessment')
    op.drop_table('medicalcondition')
    op.drop_table('client')
    # ### end Alembic commands ###
