"""Adde generate_duration field to Feedback table

Revision ID: 3c17feb44576
Revises: 297ac4f87b47
Create Date: 2026-04-01 09:17:08.533636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c17feb44576'
down_revision: Union[str, Sequence[str], None] = '297ac4f87b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assessment', ['id'])
    op.add_column('assessmentfeedback', sa.Column('generate_duration', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'assessmentfeedback', ['id'])
    op.create_unique_constraint(None, 'client', ['id'])
    op.create_unique_constraint(None, 'encountercondition', ['id'])
    op.create_unique_constraint(None, 'medicalcondition', ['id'])
    op.create_unique_constraint(None, 'physicalexam', ['id'])
    op.create_unique_constraint(None, 'toddlerexam', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'toddlerexam', type_='unique')
    op.drop_constraint(None, 'physicalexam', type_='unique')
    op.drop_constraint(None, 'medicalcondition', type_='unique')
    op.drop_constraint(None, 'encountercondition', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'assessmentfeedback', type_='unique')
    op.drop_column('assessmentfeedback', 'generate_duration')
    op.drop_constraint(None, 'assessment', type_='unique')
    # ### end Alembic commands ###
